# Site settings
title: Parrot Dev Blog
email: developers@parrot.com
description: > # this means to ignore newlines until "baseurl:"
  Parrot Blog for Developers : News from the inside !
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://developer.parrot.com" # the base hostname & protocol for your site
twitter_username: ParrotDeveloper
github_username:  Parrot-Developers

# Build settings
markdown: kramdown
